### ISSUE TITLE
It works, with no issues

### ISSUE THREAD

**Issue by st1905** [Snawoot/firefox-secure-proxy#3]
I just used HAProxy without the docker container and it worked fine. (For some reason docker container gave me some headache (stub-server_haproxy_1 exited with code 1) so i used local HAProxy binary)

OS = FreeBSD

![Screenshot from 2020-02-27 01-32-59](https://user-images.githubusercontent.com/4885199/75394499-512d8b00-5901-11ea-9e5d-f6aedeb0d313.png)

**Comment by st1905** [comment]
I am now receiving "bad request" "unknown client"
![Screenshot from 2020-02-27 23-43-22](https://user-images.githubusercontent.com/4885199/75485067-12f4a200-59bb-11ea-8199-aa09ae2f8da9.png)

**Comment by Snawoot** [comment]
Looks like they have disabled old beta-version app which had no time limits and pushing new with free 12 hours per month limitation. I guess this entire project can be archived now because it's not useful anymore.
